In [1]:
import pandas as pd

In [2]:
original = pd.read_csv("../MONALOG/SICK_corrected.tsv",sep="\t")
original = original.rename(columns={'pair_ID':"Id"})
original

,Id,sentence_A,sentence_B,entailment_label,relatedness_score,entailment_AB,entailment_BA,sentence_A_original,sentence_B_original,sentence_A_dataset,sentence_B_dataset,SemEval_set,label_kalouli,label_current_paper
0,1,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,NEUTRAL,4.5,A_neutral_B,B_neutral_A,"A group of children playing in a yard, a man i...","A group of children playing in a yard, a man i...",FLICKR,FLICKR,TRAIN,NEUTRAL,NEUTRAL
1,2,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,NEUTRAL,3.2,A_contradicts_B,B_neutral_A,"A group of children playing in a yard, a man i...","A group of children playing in a yard, a man i...",FLICKR,FLICKR,TRAIN,NEUTRAL,NEUTRAL
2,3,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,ENTAILMENT,4.7,A_entails_B,B_entails_A,"The children are playing outdoors, while a man...","The children are playing outdoors, while a man...",FLICKR,FLICKR,TRAIN,ENTAILMENT,ENTAILMENT
3,4,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,CONTRADICTION,3.6,A_contradicts_B,B_contradicts_A,"The children are playing outdoors, while a man...","The children are playing outdoors, while a man...",FLICKR,FLICKR,TRIAL,CONTRADICTION,CONTRADICTION
4,5,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,NEUTRAL,3.4,A_neutral_B,B_neutral_A,"A group of children playing in a yard, a man i...","The children are playing outdoors, while a man...",FLICKR,FLICKR,TRAIN,NEUTRAL,NEUTRAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,9996,A man is in a parking lot and is playing tenni...,The snowboarder is leaping fearlessly over whi...,NEUTRAL,1.0,A_neutral_B,B_neutral_A,A man is playing tennis with himself against a...,A snowboarder launches into the air over white...,FLICKR,FLICKR,TEST,NEUTRAL,NEUTRAL
9836,9997,Someone is boiling okra in a pot,The man is not playing the drums,NEUTRAL,1.0,A_neutral_B,B_neutral_A,someone is boiling okra in a pot,the man is playing the drums,SEMEVAL,SEMEVAL,TRAIN,NEUTRAL,NEUTRAL
9837,9998,The man is singing heartily and playing the gu...,A bicyclist is holding a bike over his head in...,NEUTRAL,1.0,A_neutral_B,B_neutral_A,the man sang and played his guitar,a bicyclist holds their bike over their head b...,SEMEVAL,FLICKR,TRAIN,NEUTRAL,NEUTRAL
9838,9999,A man in blue has a yellow ball in the mitt,A man is jumping rope outside,NEUTRAL,1.2,A_neutral_B,B_neutral_A,a man is jumping rope outside,a woman in blue has a yellow ball in her mitt,SEMEVAL,FLICKR,TRAIN,NEUTRAL,NEUTRAL
9839,10000,Three dogs are resting on a sidewalk,The woman with a knife is slicing a pepper,NEUTRAL,1.0,A_neutral_B,B_neutral_A,a woman with a knife is slicing a pepper,three dogs on a sidewalk,SEMEVAL,FLICKR,TRAIN,NEUTRAL,NEUTRAL

In [3]:
data =  pd.read_csv("SICK_cured_20221112.csv")
data

,Id,SentenceA,SentenceB,Origin,Logic_label,Commonsense_label,SICK_original,monalog,gkr4nli,langpro,ccg2lambda_easyccg,ccg2lambda_candc
0,1,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,SICK,N,N,N,N,N,N,N,N
1,2,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,SICK,C,C,C,N,N,C,C,C
2,3,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,SICK,E,E,E,N,N,N,N,N
3,4,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,SICK,C,C,C,N,C,C,C,C
4,5,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,SICK,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...
9922,5364,A man is playing a flute,There is no man playing a flute,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9923,3423,There is no man playing a harp,A man is playing a harp,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9924,4585,A woman is riding a horse,There is no woman riding a horse,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9925,4581,A woman is riding a horse,A woman is not riding a horse,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9926,1368,There is no man playing a keyboard,A man is playing a keyboard,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN

In [4]:
data.tail(88)

,Id,SentenceA,SentenceB,Origin,Logic_label,Commonsense_label,SICK_original,monalog,gkr4nli,langpro,ccg2lambda_easyccg,ccg2lambda_candc
9839,10000,Three dogs are resting on a sidewalk,The woman with a knife is slicing a pepper,SICK,N,N,N,N,N,N,N,N
9840,3713,A toy train is striking a toy car,A toy train is hitting a toy car,SemEval,E,E,E,NaN,NaN,NaN,NaN,NaN
9841,3496,A dog is walking away from a baby,A dog is licking a baby,SemEval,C,C,N,NaN,NaN,NaN,NaN,NaN
9842,3494,There is no dog licking a baby,A dog is licking a baby,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9843,5508,There is no man playing guitar,A man is playing guitar,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
9922,5364,A man is playing a flute,There is no man playing a flute,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9923,3423,There is no man playing a harp,A man is playing a harp,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9924,4585,A woman is riding a horse,There is no woman riding a horse,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9925,4581,A woman is riding a horse,A woman is not riding a horse,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN
9926,1368,There is no man playing a keyboard,A man is playing a keyboard,SemEval,C,C,C,NaN,NaN,NaN,NaN,NaN

In [5]:
data_complete = pd.merge( data,original, on='Id', how='left')[['Id', 'sentence_A', 'sentence_B', 'SentenceA', 'SentenceB', 
        'Origin','SemEval_set', 'entailment_label', 'label_kalouli','label_current_paper',                                        
       'Logic_label', 'Commonsense_label', 'SICK_original', 'monalog',
       'gkr4nli', 'langpro', 'ccg2lambda_easyccg', 'ccg2lambda_candc']]
data_complete

,Id,sentence_A,sentence_B,SentenceA,SentenceB,Origin,SemEval_set,entailment_label,label_kalouli,label_current_paper,Logic_label,Commonsense_label,SICK_original,monalog,gkr4nli,langpro,ccg2lambda_easyccg,ccg2lambda_candc
0,1,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
1,2,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,C,C,C,N,N,C,C,C
2,3,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,SICK,TRAIN,ENTAILMENT,ENTAILMENT,ENTAILMENT,E,E,E,N,N,N,N,N
3,4,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,SICK,TRIAL,CONTRADICTION,CONTRADICTION,CONTRADICTION,C,C,C,N,C,C,C,C
4,5,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9922,5364,NaN,NaN,A man is playing a flute,There is no man playing a flute,SemEval,NaN,NaN,NaN,NaN,C,C,C,NaN,NaN,NaN,NaN,NaN
9923,3423,NaN,NaN,There is no man playing a harp,A man is playing a harp,SemEval,NaN,NaN,NaN,NaN,C,C,C,NaN,NaN,NaN,NaN,NaN
9924,4585,NaN,NaN,A woman is riding a horse,There is no woman riding a horse,SemEval,NaN,NaN,NaN,NaN,C,C,C,NaN,NaN,NaN,NaN,NaN
9925,4581,NaN,NaN,A woman is riding a horse,A woman is not riding a horse,SemEval,NaN,NaN,NaN,NaN,C,C,C,NaN,NaN,NaN,NaN,NaN
9926,1368,NaN,NaN,There is no man playing a keyboard,A man is playing a keyboard,SemEval,NaN,NaN,NaN,NaN,C,C,C,NaN,NaN,NaN,NaN,NaN

In [6]:
data_complete=data_complete[data_complete["SemEval_set"].isin(['TRAIN', 'TRIAL', 'TEST'])]

In [7]:
data_complete

,Id,sentence_A,sentence_B,SentenceA,SentenceB,Origin,SemEval_set,entailment_label,label_kalouli,label_current_paper,Logic_label,Commonsense_label,SICK_original,monalog,gkr4nli,langpro,ccg2lambda_easyccg,ccg2lambda_candc
0,1,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
1,2,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,C,C,C,N,N,C,C,C
2,3,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,SICK,TRAIN,ENTAILMENT,ENTAILMENT,ENTAILMENT,E,E,E,N,N,N,N,N
3,4,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,SICK,TRIAL,CONTRADICTION,CONTRADICTION,CONTRADICTION,C,C,C,N,C,C,C,C
4,5,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,9996,A man is in a parking lot and is playing tenni...,The snowboarder is leaping fearlessly over whi...,A man is in a parking lot and is playing tenni...,The snowboarder is leaping fearlessly over whi...,SICK,TEST,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9836,9997,Someone is boiling okra in a pot,The man is not playing the drums,Someone is boiling okra in a pot,The man is not playing the drums,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9837,9998,The man is singing heartily and playing the gu...,A bicyclist is holding a bike over his head in...,The man is singing heartily and playing the gu...,A bicyclist is holding a bike over his head in...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9838,9999,A man in blue has a yellow ball in the mitt,A man is jumping rope outside,A man in blue has a yellow ball in the mitt,A man is jumping rope outside,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9839,10000,Three dogs are resting on a sidewalk,The woman with a knife is slicing a pepper,Three dogs are resting on a sidewalk,The woman with a knife is slicing a pepper,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N

In [8]:
data_complete = data_complete.reset_index(drop=True)
data_complete

,Id,sentence_A,sentence_B,SentenceA,SentenceB,Origin,SemEval_set,entailment_label,label_kalouli,label_current_paper,Logic_label,Commonsense_label,SICK_original,monalog,gkr4nli,langpro,ccg2lambda_easyccg,ccg2lambda_candc
0,1,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,A group of kids is playing in a yard and an ol...,A group of boys in a yard is playing and a man...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
1,2,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,A group of children is playing in the house an...,A group of kids is playing in a yard and an ol...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,C,C,C,N,N,C,C,C
2,3,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,The young boys are playing outdoors and the ma...,The kids are playing outdoors near a man with ...,SICK,TRAIN,ENTAILMENT,ENTAILMENT,ENTAILMENT,E,E,E,N,N,N,N,N
3,4,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,The young boys are playing outdoors and the ma...,There is no boy playing outdoors and there is ...,SICK,TRIAL,CONTRADICTION,CONTRADICTION,CONTRADICTION,C,C,C,N,C,C,C,C
4,5,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,The kids are playing outdoors near a man with ...,A group of kids is playing in a yard and an ol...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9835,9996,A man is in a parking lot and is playing tenni...,The snowboarder is leaping fearlessly over whi...,A man is in a parking lot and is playing tenni...,The snowboarder is leaping fearlessly over whi...,SICK,TEST,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9836,9997,Someone is boiling okra in a pot,The man is not playing the drums,Someone is boiling okra in a pot,The man is not playing the drums,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9837,9998,The man is singing heartily and playing the gu...,A bicyclist is holding a bike over his head in...,The man is singing heartily and playing the gu...,A bicyclist is holding a bike over his head in...,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9838,9999,A man in blue has a yellow ball in the mitt,A man is jumping rope outside,A man in blue has a yellow ball in the mitt,A man is jumping rope outside,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N
9839,10000,Three dogs are resting on a sidewalk,The woman with a knife is slicing a pepper,Three dogs are resting on a sidewalk,The woman with a knife is slicing a pepper,SICK,TRAIN,NEUTRAL,NEUTRAL,NEUTRAL,N,N,N,N,N,N,N,N

In [9]:
data_complete.columns

Index(['Id', 'sentence_A', 'sentence_B', 'SentenceA', 'SentenceB', 'Origin',
       'SemEval_set', 'entailment_label', 'label_kalouli',
       'label_current_paper', 'Logic_label', 'Commonsense_label',
       'SICK_original', 'monalog', 'gkr4nli', 'langpro', 'ccg2lambda_easyccg',
       'ccg2lambda_candc'],
      dtype='object')

In [10]:
data=data_complete.copy()

In [11]:
data.to_pickle("all.pickle")

In [12]:
dev=data[data["SemEval_set"]=="TRIAL"][["SentenceA","SentenceB","entailment_label", 'Origin',
       'SemEval_set', 'entailment_label', 'label_kalouli',
       'label_current_paper', 'Logic_label', 'Commonsense_label',
       'SICK_original', 'monalog', 'gkr4nli', 'langpro', 'ccg2lambda_easyccg',
       'ccg2lambda_candc']].rename(columns={'SentenceA': 'sentence1','SentenceB': 'sentence2','entailment_label': 'gold_label'}).reset_index(drop=True)
train=data[data["SemEval_set"]=="TRAIN"][["SentenceA","SentenceB","entailment_label", 'Origin',
       'SemEval_set', 'entailment_label', 'label_kalouli',
       'label_current_paper', 'Logic_label', 'Commonsense_label',
       'SICK_original', 'monalog', 'gkr4nli', 'langpro', 'ccg2lambda_easyccg',
       'ccg2lambda_candc']].rename(columns={'SentenceA': 'sentence1','SentenceB': 'sentence2','entailment_label': 'gold_label'}).reset_index(drop=True)
test=data[data["SemEval_set"]=="TEST"][["SentenceA","SentenceB","entailment_label", 'Origin',
       'SemEval_set', 'entailment_label', 'label_kalouli',
       'label_current_paper', 'Logic_label', 'Commonsense_label',
       'SICK_original', 'monalog', 'gkr4nli', 'langpro', 'ccg2lambda_easyccg',
       'ccg2lambda_candc']].rename(columns={'SentenceA': 'sentence1','SentenceB': 'sentence2','entailment_label': 'gold_label'}).reset_index(drop=True)
dev.to_csv("SICK_DEV_1.csv", index=False)
test.to_csv("SICK_TEST_1.csv", index=False)
train.to_csv("SICK_TRAIN_1.csv", index=False)